### PR TITLE
Quantum Prisoner's Dilemma

### PR DESCRIPTION
**Pull request by MH2520**

### CODE REVIEW

**Comment by AnthonyBordg** [comment]
Dear @MH2520 ,

the current PR tries to push not only `Quantum_Prisoners_Dilemma.thy`, but also `Quantum_Fourier_Transform.thy`.

**Comment by MH2520** [comment]
What should I do to only push the file `Quantum_Prisoners_Dilemma.thy`? I just made a new branch without `Quantum_Fourier_Transform.thy` in my fork, but I am worried that using it may cause problems when `Quantum_Fourier_Transform.thy` is finished and pushed to the main fork.

**Comment by Lachnitt** [comment]
Hey :) I had a similar problem before. Its best to always use a new branch for each theory you are working on. 
For now you might want to have a look at  `git rebase -i`or if there are only few commits  `git cherry-pick` (see here: https://poanchen.github.io/blog/2017/11/12/How-to-create-a-GitHub-pull-request-with-a-specific-commits). Did I send you my Quantum Prisoner's Dilemma file per mail back then?

**Comment by AnthonyBordg** [comment]
> What should I do to only push the file `Quantum_Prisoners_Dilemma.thy`? I just made a new branch without `Quantum_Fourier_Transform.thy` in my fork, but I am worried that using it may cause problems when `Quantum_Fourier_Transform.thy` is finished and pushed to the main fork.

It should be ok, you will simply need to remove the file `Quantum_Prisoners_Dilemma.thy` from your first branch before pushing `Quantum_Fourier_Transform.thy`. Of course, in the history there will be ghost commits, but if you don't want to bother just close this PR and open a new one based on your new branch prisoners_dilemma_only.
When one starts a new project it's better to do it in a new branch. In your case, since the quantum prisoners's dilemma does not require your work on the quantum Fourier transform, there is no reason of not using a new branch.

**Pull request closed without merging**
