### PR TITLE
ROOTS file

### PR DESCRIPTION
**Pull request by jaycech3n**

### CODE REVIEW

**Comment by jaycech3n** [comment]
Actually, I think it might be better to base this off the Jordan_Normal_Form session. Let me experiment with this first.

**Comment by jaycech3n** [comment]
Jordan_Normal_Form indeed seems a suitable session to base off.

**Comment by AnthonyBordg** [comment]
@jaycech3n Thanks a lot for the root file.
Do you think it's ok to have several sessions given the fact that in the [root file](https://bitbucket.org/isa-afp/afp-2018/src/default/thys/Example-Submission/ROOT) of the example submission one reads that 

> It is strongly encouraged to have precisely one session, but it
   if needed, further sessions are permitted.

**Comment by jaycech3n** [comment]
I'm not an expert, but I believe the strong encouragement is for one *toplevel* session defined per AFP submission (in this case, `Isabelle_marries_Dirac`), while multiple session imports are fine.

If you intend submission to the AFP, then (AFP) should also be added after the session name.

**Comment by AnthonyBordg** [comment]
@jaycech3n It makes sense, thanks.
Oddly enough, there is in your pull request 1,843 additions in `Quantum.thy` and 471 in `Tensor.thy`, while there is nothing new added to these theories. 
Can you please fix that ?

**Comment by jaycech3n** [comment]
Hmm, that's weird.. I think that's the result of me syncing my old fork with the latest commits from yours. But good point, I don't think I can change that on this PR so I'll close this and open a new one without the ghost additions.

**Pull request closed without merging**
