### PR TITLE
Deutsch_Jozsa_Algorithm

### PR DESCRIPTION
**Pull request by Lachnitt**
Update

### CODE REVIEW

**Comment by AnthonyBordg** [comment]
@Lachnitt 
Dear Hanna, I'm sorry but due to the recent changes, there are now some conflicts that must be resolved. Can you do that ?

**Comment by Lachnitt** [comment]
Its easier to open a new pull request

**Comment by AnthonyBordg** [comment]
@Lachnitt the problem is still the same, since you only reverted the commit, hence `More_Tensor` is replaced by `MoreTensor`. Instead of using `git revert`, if you use `git reset --hard` then you will lose the commits made after Josh's commit.
We need to discuss the best solution.
@MH2520 will certainly have the same problem in the future.

**Comment by Lachnitt** [comment]
Sry I paused to join Theory Tea. Yes this is because I reset the head to a point before the renaming happend. I will proceed with it now.

**Comment by Lachnitt** [comment]
Nathanel knows more about git than me and is going to help me :)

**Comment by Lachnitt** [comment]
See new pull request.

**Pull request closed without merging**
